### PR TITLE
Adding x86 asm using the Windows API

### PR DESCRIPTION
**Pull request by just6chill**

### CODE REVIEW

**Comment by PQCraft** [comment]
@just6chill spelling error:
```
msg db "Hello Wold"
```
->
```
msg db "Hello World"
```
or
```
msg db "Hello, World!"
```

**Comment by just6chill** [comment]
@PQCraft Thank you, I fixed it

**Comment by nguyenphuminh** [comment]
Don't really know asm but cool I guess.

**Comment by nguyenphuminh** [comment]
Please check out my main stuff if you like: https://github.com/FreakC-Foundation/FreakC

**Pull request merged**
