### PR TITLE
Added Fortan Hello World

### PR DESCRIPTION
**Pull request by kacperks**

### CODE REVIEW

**Comment by nguyenphuminh** [comment]
It looks like the language's name is incorrect.

**Comment by kacperks** [comment]
https://en.wikipedia.org/wiki/Fortran#:~:text=Fortran%20(%2F%CB%88f%C9%94%CB%90rt,numeric%20computation%20and%20scientific%20computing.

**Comment by nguyenphuminh** [comment]
Fortran not Fortan

**Comment by kacperks** [comment]
oh ok lol

**Comment by kacperks** [comment]
i will send new pull request with correct name

**Comment by JavaCode7** [comment]
The name is not the easiest to spell, I actually pronounce it as Fortan.

**Pull request closed without merging**
